<?php

/**
 * @file
 * Contains performance_tests.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function performance_tests_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the performance_tests module.
    case 'help.page.performance_tests':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Performance tests') . '</p>';
      return $output;

    default:
  }
}


function performance_tests_preprocess_block(&$variables) {
    // kint($variables);
    if(isset($_GET['dump_vars'])){
      kint($variables['#cache']);
      $variables['#cache']['contexts'] = [];
      kint($variables['content']);
    }
}
